package di03_solucion_tarea;


import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componenteRelojBean2 = new componentes.ComponenteRelojBean();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        componenteRelojBean2.setActivar_Alarma(true);
        componenteRelojBean2.setHora_Alarma(11);
        componenteRelojBean2.setMinutos_Alarma(56);
        componenteRelojBean2.addDefinirAlarmaListener(new componentes.ComponenteRelojBean.DefinirAlarmaListener() {
            public void capturarAlarma(componentes.DefinirAlarmaEvent evt) {
                componenteRelojBean2CapturarAlarma(evt);
            }
        });
        getContentPane().add(componenteRelojBean2);
        componenteRelojBean2.setBounds(150, 110, 62, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void componenteRelojBean2CapturarAlarma(componentes.DefinirAlarmaEvent evt) {//GEN-FIRST:event_componenteRelojBean2CapturarAlarma
        // TODO add your handling code here:
          JOptionPane.showMessageDialog(null, "La cuenta atrás ha terminado", "Aviso",
        JOptionPane.INFORMATION_MESSAGE);
          componenteRelojBean2.activar_Alarma=false;
    }//GEN-LAST:event_componenteRelojBean2CapturarAlarma

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.ComponenteRelojBean componenteRelojBean2;
    // End of variables declaration//GEN-END:variables
}
