/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorEjercicio4;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class Vejercicio4 extends javax.swing.JFrame {

    /**
     * Creates new form Vejercicio4
     */
    public Vejercicio4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDep_Insertar = new javax.swing.JButton();
        btnDep_Borrar = new javax.swing.JButton();
        btnDep_Modificarr = new javax.swing.JButton();
        txtDep_Nombre = new javax.swing.JTextField();
        txtDep_No = new javax.swing.JTextField();
        txtDep_Loca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nº :");

        jLabel2.setText("Nombre :");

        jLabel3.setText("Localización :");

        jLabel4.setText("Departamento");

        btnDep_Insertar.setText("Añadir");
        btnDep_Insertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDep_InsertarMouseClicked(evt);
            }
        });

        btnDep_Borrar.setText("Borrar");
        btnDep_Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDep_BorrarMouseClicked(evt);
            }
        });

        btnDep_Modificarr.setText("Modificar");

        txtDep_No.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDep_NoFocusLost(evt);
            }
        });

        jButton1.setText("Borrar ALL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDep_Loca)
                    .addComponent(txtDep_Nombre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDep_No, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDep_Modificarr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDep_Borrar)
                    .addComponent(btnDep_Insertar))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnDep_Insertar)
                    .addComponent(txtDep_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnDep_Borrar)
                    .addComponent(txtDep_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnDep_Modificarr)
                    .addComponent(txtDep_Loca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDep_NoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDep_NoFocusLost
    ControladorEjercicio4.rellenarCampos();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDep_NoFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
ControladorEjercicio4.finalizarSession();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
ControladorEjercicio4.iniciarSession();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnDep_InsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDep_InsertarMouseClicked
ControladorEjercicio4.insertarDepartamento();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDep_InsertarMouseClicked

    private void btnDep_BorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDep_BorrarMouseClicked
ControladorEjercicio4.borrarDepartamento();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDep_BorrarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
ControladorEjercicio4.borrarDepartamentoConEmpleados();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public JTextField getTxtDep_Loca() {
        return txtDep_Loca;
    }

    public void setTxtDep_Loca(JTextField txtDep_Loca) {
        this.txtDep_Loca = txtDep_Loca;
    }

    public JTextField getTxtDep_No() {
        return txtDep_No;
    }

    public void setTxtDep_No(JTextField txtDep_No) {
        this.txtDep_No = txtDep_No;
    }

    public JTextField getTxtDep_Nombre() {
        return txtDep_Nombre;
    }

    public void setTxtDep_Nombre(JTextField txtDep_Nombre) {
        this.txtDep_Nombre = txtDep_Nombre;
    }

    public JButton getBtnDep_Borrar() {
        return btnDep_Borrar;
    }

    public JButton getBtnDep_Insertar() {
        return btnDep_Insertar;
    }

    public JButton getBtnDep_Modificarr() {
        return btnDep_Modificarr;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDep_Borrar;
    private javax.swing.JButton btnDep_Insertar;
    private javax.swing.JButton btnDep_Modificarr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDep_Loca;
    private javax.swing.JTextField txtDep_No;
    private javax.swing.JTextField txtDep_Nombre;
    // End of variables declaration//GEN-END:variables
}
